[files]
extend-exclude = [
    ".git/",
    "composer.lock",
    "yarn.lock",
    "nova-components/*/dist/",
]
ignore-hidden = false

[default.extend-words]
"encrypter" = "encrypter"
"invokable" = "invokable"
"responsable" = "responsable"
